# Generated by Django 5.1.2 on 2024-10-29 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-publish',), 'verbose_name': 'Post', 'verbose_name_plural': 'Posts'},
        ),
    ]
